### ISSUE TITLE
Blacken-docs does not work with tabbed indentation

### ISSUE THREAD

**Issue by jpfeuffer** [adamchainz/blacken-docs#216]
### Python Version

3.10

### Package Version

1.13.0

### Description

```
.. code-block: python
    
    def foo():
        pass
```

where the indentation are tabs. Rst recommends spaces but allows tabs. Blacken does not and fails.

```
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/blacken_docs/__init__.py", line 293, in main
    retv |= format_file(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/blacken_docs/__init__.py", line 236, in format_file
    new_contents, errors = format_str(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/blacken_docs/__init__.py", line 215, in format_str
    src = RST_RE.sub(_rst_match, src)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/blacken_docs/__init__.py", line 122, in _rst_match
    min_indent = min(INDENT_RE.findall(match["code"]))
ValueError: min() arg is an empty sequence
```

Would be great if:

- blacken allows tabs
- has better error handling when looking for min/max indentation in general

**Comment by adamchainz** [comment]
Just realized #108 is a duplicate (it had a poor title). Closing this in favour of the older issue number.
